### ISSUE TITLE
missing import traceback line 84

### ISSUE THREAD

**Issue by johnnyWalnut** [zmap/celerybeat-mongo#24]
```2017-01-18 15:18:50,229 CRITICAL MainThread beat - start_scheduler: beat raised exception <type 'exceptions.NameError'>: NameError("global name 'traceback' is not defined",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/apps/beat.py", line 112, in start_scheduler
    beat.start()
  File "/usr/lib/python2.7/site-packages/celery/beat.py", line 472, in start
    self.sync()
  File "/usr/lib/python2.7/site-packages/celery/beat.py", line 475, in sync
    self.scheduler.close()
  File "/usr/lib/python2.7/site-packages/celery/beat.py", line 285, in close
    self.sync()
  File "/src/celerybeat-mongo/celerybeatmongo/schedulers.py", line 145, in sync
    entry.save()
  File "/src/celerybeat-mongo/celerybeatmongo/schedulers.py", line 84, in save
    get_logger(__name__).error(traceback.format_exc())
NameError: global name 'traceback' is not defined```

fixed:

**Comment by zakird** [comment]
This is fixed by #25
